version: '3'

services:
  app:
    build: .docker/.docker-node
    entrypoint: .docker/entrypoint.sh
    container_name: history-world-app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /back-end:/usr/src/app
    #command: 'npm run start:dev'
    depends_on:
      - db

  db:
    build: .docker/.docker-mysql
    container_name: history-world-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - '${DATABASE_PORT}:3333'
    volumes:
      - .docker/mysql-data:/usr/src/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
