version: '3'

services:
  app:
    build: ./back-end
    entrypoint: ./back-end/.docker/entrypoint.sh
    container_name: history-world-app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - TZ=America/Sao_Paulo
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./back-end:/usr/src/app
    #command: 'npm run start:dev'
    depends_on:
      - db
    env_file:
      - ./back-end/.env

  db:
    build: ./back-end/.docker/.docker-mysql
    container_name: history-world-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - '${DATABASE_PORT}:3333'
    volumes:
      - ./back-end/.docker/mysql-data:/usr/src/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - ./back-end/.env
